add FILE /home/ckekeh/src/W205/W205Exercise1/transforming/transform_surveys_responses.py;

use exercise1;

CREATE TABLE transformed_surveys_responses AS
SELECT TRANSFORM
(PROVIDERID,
COMM_WITH_NURSES_ACHIEV,
COMM_WITH_DOCTORS_ACHIEV,
RESPONS_HOSP_STAFF_ACHIEV,
PAIN_MANAG_ACHIEV,
COMM_MEDICINES_ACHIEV,
CLEAN_AND_QUIET_ACHIEV,
DISCHARGE_INFO_ACHIEVE,
OVERALL_RATING_ACHIEV,
HCAHPS_BASE_SCORE, HCAHPS_CONSISTENCY_SCORE)
USING 'python transform_surveys_responses.py' AS
(PROVIDERID string, COMM_WITH_NURSES_ACHIEV float, 
COMM_WITH_DOCTORS_ACHIEV float, RESPONS_HOSP_STAFF_ACHIEV float,
PAIN_MANAG_ACHIEV float, COMM_MEDECINES_ACHIEV float,
CLEAN_AND_QUIET_ACHIEV float, DISCHARGE_INFO_ACHIEVE float, 
OVERALL_RATING_ACHIEV float, HCAHPS_BASE_SCORE string, 
HPAHCS_CONSISTENCY_SCORE string)
FROM surveys_responses;
